// Auto-generated by build.rs. Do not edit.

/// Embedded _engine Lua scripts for new game projects.
pub static ENGINE_SCRIPTS: &[(&str, &str)] = &[
    ("data/components.lua", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/scripts/_engine/data/components.lua"))),
    ("data/direction.lua", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/scripts/_engine/data/direction.lua"))),
    ("data/input.lua", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/scripts/_engine/data/input.lua"))),
    ("data/menus.lua", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/scripts/_engine/data/menus.lua"))),
    ("globals.lua", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/scripts/_engine/globals.lua"))),
    ("runtime/audio.lua", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/scripts/_engine/runtime/audio.lua"))),
    ("runtime/engine.lua", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/scripts/_engine/runtime/engine.lua"))),
    ("runtime/entity.lua", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/scripts/_engine/runtime/entity.lua"))),
    ("runtime/save.lua", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/scripts/_engine/runtime/save.lua"))),
    ("runtime/script.lua", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/scripts/_engine/runtime/script.lua"))),
    ("runtime/text.lua", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/scripts/_engine/runtime/text.lua"))),
    ("ui/color.lua", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/scripts/_engine/ui/color.lua"))),
    ("ui/menu.lua", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/scripts/_engine/ui/menu.lua"))),
    ("ui/theme.lua", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/scripts/_engine/ui/theme.lua"))),
];
