mod clear_speech;
mod despawn;
mod interact;
mod move_by;
mod play_sound;
mod reset_clip;
mod say;
mod set;
mod set_anim_speed;
mod set_clip;
mod set_facing;
mod set_flip_x;
mod set_sound_volume;
mod stop_sound;
mod teleport;

pub(super) use clear_speech::ClearSpeechMethod;
pub(super) use despawn::DespawnMethod;
pub(super) use interact::InteractMethod;
pub(super) use move_by::MoveByMethod;
pub(super) use play_sound::PlaySoundMethod;
pub(super) use reset_clip::ResetClipMethod;
pub(super) use say::SayMethod;
pub(super) use set::SetMethod;
pub(super) use set_anim_speed::SetAnimSpeedMethod;
pub(super) use set_clip::SetClipMethod;
pub(super) use set_facing::SetFacingMethod;
pub(super) use set_flip_x::SetFlipXMethod;
pub(super) use set_sound_volume::SetSoundVolumeMethod;
pub(super) use stop_sound::StopSoundMethod;
pub(super) use teleport::TeleportMethod;
