use super::{
    load_startup_for_game_name, load_startup_from_resources,
    runtime_icon::playtest_game_name_from_payload as parse_playtest_game_name, StartupAsset,
    StartupScreenContent, StartupScreenSpec,
};
use crate::engine::{Engine, EngineBuilder, EngineEntryMode, GameInstance};
use bishop::prelude::*;
use engine_core::prelude::*;
use ron::de::from_str;
use std::fs;
use std::path::{Path, PathBuf};

/// The source for runtime startup.
pub enum StartupSource {
    /// Load the shipped game from the game binary's `Resources/` folder.
    Game,
    /// Load a playtest payload generated by the editor.
    Playtest {
        payload_path: String,
    },
}

#[derive(serde::Deserialize)]
struct PlaytestPayload {
    room: Room,
    game: Game,
    startup_ron: Option<String>,
    #[serde(default)]
    startup_mode: StartupMode,
}

struct LoadedPlaytestData {
    startup_asset: StartupAsset,
    room: Room,
    game: Game,
    startup_mode: StartupMode,
}

#[allow(clippy::large_enum_variant)]
enum LoadedStartupData {
    Game {
        startup_asset: StartupAsset,
        game: Game,
    },
    Playtest(LoadedPlaytestData),
}

enum LoadedStartupFiles {
    Game {
        resources_dir: PathBuf,
        startup_ron: Option<String>,
        game_ron: String,
    },
    Playtest {
        payload_ron: String,
    },
}

/// Bootstrap controller that renders startup screens until the runtime `Engine` is ready.
pub struct StartupController {
    startup_asset: StartupAsset,
    load_task: BackgroundTask<Result<LoadedStartupFiles, String>>,
    loaded: Option<LoadedStartupData>,
    splash_index: usize,
    splash_started_at_secs: Option<f64>,
    fallback_started_at_secs: Option<f64>,
    error: Option<String>,
}

impl StartupController {
    /// Creates a startup controller for the given source.
    pub fn new(source: StartupSource) -> Self {
        let startup_asset = load_initial_startup(&source);
        Self {
            startup_asset,
            load_task: BackgroundTask::spawn(move || load_startup_data(source)),
            loaded: None,
            splash_index: 0,
            splash_started_at_secs: None,
            fallback_started_at_secs: None,
            error: None,
        }
    }

    /// Advances bootstrap and returns the fully-built engine once ready.
    pub async fn frame(&mut self, ctx: PlatformContext) -> Option<Engine> {
        if let Some(error) = &self.error {
            render_error_screen(&ctx, error);
            return None;
        }

        if self.loaded.is_none() {
            if let Some(result) = self.load_task.poll() {
                match result {
                    Ok(files) => match parse_startup_data(files) {
                        Ok(loaded) => {
                            self.startup_asset = loaded.startup_asset().clone();
                            self.loaded = Some(loaded);
                        }
                        Err(error) => self.error = Some(error),
                    },
                    Err(error) => {
                        self.error = Some(error);
                    }
                }
            }
        }

        if let Some(error) = &self.error {
            render_error_screen(&ctx, error);
            return None;
        }

        if self
            .loaded
            .as_ref()
            .is_some_and(LoadedStartupData::skips_startup_presentation)
        {
            let loaded = self.loaded.take()?;
            return Some(build_engine(ctx, loaded));
        }

        if let Some(screen) = self.startup_asset.loading.splash_screens.get(self.splash_index) {
            render_screen(&ctx, screen);
            let now = ctx.borrow().get_time();
            let started_at = self.splash_started_at_secs.get_or_insert(now);
            if splash_min_duration_elapsed(*started_at, now, screen.min_duration_secs) {
                self.splash_started_at_secs = None;
                self.splash_index += 1;
            }
            return None;
        }

        render_screen(&ctx, &self.startup_asset.loading.fallback_screen);

        let now = ctx.borrow().get_time();
        let started_at = self.fallback_started_at_secs.get_or_insert(now);
        if !splash_min_duration_elapsed(
            *started_at,
            now,
            self.startup_asset.loading.fallback_screen.min_duration_secs,
        ) {
            return None;
        }

        self.fallback_started_at_secs = None;
        let loaded = self.loaded.take()?;
        Some(build_engine(ctx, loaded))
    }
}

impl LoadedStartupData {
    fn startup_asset(&self) -> &StartupAsset {
        match self {
            Self::Game { startup_asset, .. } => startup_asset,
            Self::Playtest(playtest) => &playtest.startup_asset,
        }
    }

    fn skips_startup_presentation(&self) -> bool {
        matches!(
            self,
            Self::Playtest(LoadedPlaytestData {
                startup_mode: StartupMode::Skip,
                ..
            })
        )
    }
}

fn load_startup_data(source: StartupSource) -> Result<LoadedStartupFiles, String> {
    match source {
        StartupSource::Game => {
            let resources_dir = resources_dir_from_exe()
                .ok_or_else(|| "Could not find game resources folder.".to_string())?;
            let startup_path = resources_dir.join("startup.ron");
            let startup_ron = fs::read_to_string(&startup_path).ok();
            let game_path = resources_dir.join(GAME_RON);
            let game_ron = fs::read_to_string(&game_path)
                .map_err(|error| format!("Could not read '{}': {error}", game_path.display()))?;
            Ok(LoadedStartupFiles::Game {
                resources_dir,
                startup_ron,
                game_ron,
            })
        }
        StartupSource::Playtest { payload_path } => {
            let payload_str = fs::read_to_string(&payload_path)
                .map_err(|error| format!("Could not read playtest payload: {error}"))?;
            Ok(LoadedStartupFiles::Playtest {
                payload_ron: payload_str,
            })
        }
    }
}

fn load_initial_startup(source: &StartupSource) -> StartupAsset {
    match source {
        StartupSource::Game => resources_dir_from_exe()
            .map(|resources_dir| load_startup_from_resources(&resources_dir))
            .unwrap_or_default(),
        StartupSource::Playtest { payload_path } => {
            load_playtest_startup_preview(Path::new(payload_path)).unwrap_or_default()
        }
    }
}

fn load_playtest_startup_preview(payload_path: &Path) -> Option<StartupAsset> {
    #[derive(serde::Deserialize)]
    struct PayloadStartupPreview {
        startup_ron: Option<String>,
    }

    let payload_ron = fs::read_to_string(payload_path).ok()?;
    let preview = from_str::<PayloadStartupPreview>(&payload_ron).ok()?;
    if let Some(startup_ron) = preview.startup_ron.as_deref() {
        return Some(parse_payload_startup(startup_ron));
    }
    let game_name = parse_playtest_game_name(&payload_ron)?;
    Some(load_startup_for_game_name(&game_name))
}

fn parse_startup_data(files: LoadedStartupFiles) -> Result<LoadedStartupData, String> {
    match files {
        LoadedStartupFiles::Game {
            resources_dir,
            startup_ron,
            game_ron,
        } => {
            let startup_asset = parse_startup(startup_ron.as_deref(), &resources_dir);
            let game =
                from_str::<Game>(&game_ron).map_err(|error| format!("Failed to parse game.ron: {error}"))?;
            Ok(LoadedStartupData::Game { startup_asset, game })
        }
        LoadedStartupFiles::Playtest { payload_ron } => {
            let PlaytestPayload {
                room,
                game,
                startup_ron,
                startup_mode,
            } = from_str(&payload_ron)
                .map_err(|error| format!("Failed to deserialize playtest payload: {error}"))?;
            let startup_asset = startup_ron
                .as_deref()
                .map(parse_payload_startup)
                .unwrap_or_else(|| load_startup_for_game_name(&game.name));
            Ok(LoadedStartupData::Playtest(LoadedPlaytestData {
                startup_asset,
                room,
                game,
                startup_mode,
            }))
        }
    }
}

fn parse_startup(startup_ron: Option<&str>, resources_dir: &Path) -> StartupAsset {
    let Some(startup_ron) = startup_ron else {
        return StartupAsset::default();
    };

    ron::from_str(startup_ron).unwrap_or_else(|error| {
        onscreen_error!(
            "Failed to parse startup '{}': {}",
            resources_dir.join("startup.ron").display(),
            error
        );
        StartupAsset::default()
    })
}

fn parse_payload_startup(startup_ron: &str) -> StartupAsset {
    ron::from_str(startup_ron).unwrap_or_else(|error| {
        onscreen_error!("Failed to parse embedded playtest startup: {}", error);
        StartupAsset::default()
    })
}

fn build_engine(ctx: PlatformContext, loaded: LoadedStartupData) -> Engine {
    match loaded {
        LoadedStartupData::Game { startup_asset, game } => {
            set_engine_mode(EngineMode::Game);
            set_game_name(game.name.clone());

            let entry_mode = resolve_entry_mode(&startup_asset, &game, StartupMode::Full);
            let mut builder = EngineBuilder::new().entry_mode(entry_mode);
            let game_instance = {
                let mut ctx_ref = ctx.borrow_mut();
                GameInstance::from_loaded_game(
                    &mut *ctx_ref,
                    game,
                    &builder.lua,
                    &mut builder.camera_manager,
                )
            };

            builder.assemble(game_instance, ctx, false)
        }
        LoadedStartupData::Playtest(LoadedPlaytestData {
            startup_asset,
            room,
            game,
            startup_mode,
        }) => {
            set_engine_mode(EngineMode::Playtest);
            set_game_name(game.name.clone());

            let mut builder = prepare_playtest_engine_builder(&startup_asset, &game, startup_mode);
            let game_instance = {
                let mut ctx_ref = ctx.borrow_mut();
                GameInstance::from_loaded_room(
                    &mut *ctx_ref,
                    room,
                    game,
                    &builder.lua,
                    &mut builder.camera_manager,
                )
            };

            builder.assemble(game_instance, ctx, true)
        }
    }
}

fn prepare_playtest_engine_builder(
    startup_asset: &StartupAsset,
    game: &Game,
    startup_mode: StartupMode,
) -> EngineBuilder {
    let entry_mode = resolve_entry_mode(startup_asset, game, startup_mode);
    EngineBuilder::new().entry_mode(entry_mode)
}

fn resolve_entry_mode(startup_asset: &StartupAsset, game: &Game, startup_mode: StartupMode) -> EngineEntryMode {
    if startup_mode == StartupMode::Skip {
        return EngineEntryMode::Playing;
    }

    let menu_id = startup_asset.start_menu_id.trim();
    if menu_id.is_empty() {
        return EngineEntryMode::Playing;
    }

    if !menu_template_exists(menu_id) {
        onscreen_error!(
            "Startup menu '{}' is missing for game '{}'; falling back to Playing.",
            menu_id,
            game.name
        );
        return EngineEntryMode::Playing;
    }

    EngineEntryMode::StartMenu {
        menu_id: menu_id.to_string(),
    }
}

fn menu_template_exists(menu_id: &str) -> bool {
    let dir = menus_folder();
    let Ok(entries) = fs::read_dir(dir) else {
        return false;
    };

    for entry in entries.filter_map(Result::ok) {
        let path = entry.path();
        if path.extension().is_none_or(|ext| ext != "ron") {
            continue;
        }
        let Ok(ron_str) = fs::read_to_string(&path) else {
            continue;
        };
        let Ok(template) = ron::from_str::<MenuTemplate>(&ron_str) else {
            continue;
        };
        if template.id == menu_id {
            return true;
        }
    }

    false
}

fn render_error_screen(ctx: &PlatformContext, error: &str) {
    let screen = StartupScreenSpec {
        min_duration_secs: 0.0,
        background_color: [0.1, 0.0, 0.0, 1.0],
        content: StartupScreenContent::Text {
            text: error.to_string(),
            font_size: 32.0,
            color: [1.0, 0.9, 0.9, 1.0],
        },
    };
    render_screen(ctx, &screen);
}

fn render_screen(ctx: &PlatformContext, screen: &StartupScreenSpec) {
    let mut ctx_ref = ctx.borrow_mut();
    let ctx = &mut *ctx_ref;
    ctx.clear_background(screen.background_color.into());

    match &screen.content {
        StartupScreenContent::Text {
            text,
            font_size,
            color,
        } => draw_centered_text(ctx, text, *font_size, (*color).into()),
    }
}

fn draw_centered_text(ctx: &mut impl BishopContext, text: &str, font_size: f32, color: Color) {
    let dims = ctx.measure_text(text, font_size);
    let x = (ctx.screen_width() - dims.width) * 0.5;
    let y = (ctx.screen_height() + dims.height) * 0.5;
    ctx.draw_text(text, x, y, font_size, color);
}

fn splash_min_duration_elapsed(started_at_secs: f64, now_secs: f64, min_duration_secs: f32) -> bool {
    (now_secs - started_at_secs) >= min_duration_secs as f64
}

#[cfg(test)]
mod tests;
