// engine_core/src/ecs/ecs.rs
use crate::ecs::component::{Component, ComponentStore};
use crate::ecs::component_registry::*;
use crate::ecs::entity::*;
use crate::ecs::has_any::HasAny;
use crate::ecs::{CurrentRoom, Player, PlayerProxy, Transform};
use crate::game::GameCtxMut;
use crate::worlds::room::RoomId;
use once_cell::sync::Lazy;
use serde::de::Deserializer;
use serde::ser::{SerializeStruct, Serializer};
use serde::{Deserialize, Serialize};
use std::any::Any;
use std::any::TypeId;
use std::collections::{HashMap, HashSet};

#[derive(Debug)]
pub struct Ecs {
    pub stores: HashMap<TypeId, Box<dyn Any + Send + Sync>>,
    pub(crate) next_entity_id: usize,
    /// Room-index: maps RoomId -> set of Entities in that room.
    pub(crate) room_entities: HashMap<RoomId, HashSet<Entity>>,
}

impl Default for Ecs {
    fn default() -> Self {
        Self {
            stores: HashMap::new(),
            next_entity_id: 1,
            room_entities: HashMap::new(),
        }
    }
}

impl Ecs {
    /// Allocate a fresh id and return a builder.
    pub fn create_entity(&mut self) -> EntityBuilder<'_> {
        let id = Entity(self.next_entity_id);
        self.next_entity_id += 1;
        EntityBuilder {
            id,
            ecs: self,
        }
    }

    /// Immutable reference to a component belonging to `entity`.
    /// Returns `None` when the entity does not have that component.
    pub fn get<T>(&self, entity: Entity) -> Option<&T>
    where
        T: Component + 'static,
    {
        self.get_store::<T>().get(entity)
    }

    /// Mutable reference to a component belonging to `entity`.
    /// Panics if the component store has never been created.
    pub fn get_mut<T>(&mut self, entity: Entity) -> Option<&mut T>
    where
        T: Component + 'static,
    {
        self.get_store_mut::<T>().get_mut(entity)
    }

    /// Check whether an entity has a component of type `T`.
    pub fn has<T>(&self, entity: Entity) -> bool
    where
        T: Component + 'static,
    {
        self.get_store::<T>().contains(entity)
    }

    /// Check whether an entity has any components in tuple `T`.
    pub fn has_any<T>(&self, entity: Entity) -> bool
    where
        T: HasAny,
    {
        T::has_any(self, entity)
    }

    /// Remove an entity and all of its descendants.
    pub fn remove_entity(ctx: &mut GameCtxMut<'_>, entity: Entity) {
        // Detach from parent (if any)
        let parent = ctx.ecs().get::<Parent>(entity).map(|p| p.0);
        if let Some(parent) = parent
            && let Some(children) = ctx.ecs().get_mut::<Children>(parent)
        {
            children.remove(entity);
            if children.entities.is_empty() {
                ctx.ecs().get_store_mut::<Children>().remove(parent);
            }
        }

        // Remove children recursively
        let children = get_children(ctx.ecs(), entity);
        for child in children {
            Ecs::remove_entity(ctx, child);
        }

        // Remove all its components
        for reg in inventory::iter::<ComponentRegistry> {
            // Run post_remove and on_remove for all components before removing them
            if (reg.has)(ctx.ecs(), entity) {
                let mut boxed = (reg.clone)(ctx.ecs(), entity);
                (reg.post_remove)(&mut *boxed, &entity, ctx);
                (reg.on_remove)(&mut *boxed, &entity, ctx.ecs());
            }

            (reg.remove)(ctx.ecs(), entity);
        }
    }

    /// Remove a single component from an entity, calling its post_remove hook.
    pub fn remove_component<T>(ctx: &mut GameCtxMut<'_>, entity: Entity)
    where
        T: Component + 'static,
    {
        let type_name = std::any::type_name::<T>().rsplit("::").next().unwrap_or("");

        // Find the registry entry for this component type
        let reg = inventory::iter::<ComponentRegistry>
            .into_iter()
            .find(|r| r.type_name == type_name);

        if let Some(reg) = reg
            && (reg.has)(ctx.ecs(), entity)
        {
            let mut boxed = (reg.clone)(ctx.ecs(), entity);
            (reg.post_remove)(&mut *boxed, &entity, ctx);
            (reg.on_remove)(&mut *boxed, &entity, ctx.ecs());
            (reg.remove)(ctx.ecs(), entity);
        }
    }

    // TODO: Is this legit?
    /// Return an immutable reference to the store for Component `T`.
    pub fn get_store<T>(&self) -> &ComponentStore<T>
    where
        T: Component + 'static,
    {
        unsafe {
            let mut_self = self as *const Self as *mut Self;
            (*mut_self).get_or_create_store::<T>()
        }
    }

    /// Return a mutable reference, creating the store on‑first‑use.
    pub fn get_store_mut<T>(&mut self) -> &mut ComponentStore<T>
    where
        T: Component + 'static,
    {
        self.get_or_create_store::<T>()
    }

    /// Used by the `Component` impl generated by the ecs_component macro.
    pub(crate) fn get_or_create_store<T>(&mut self) -> &mut ComponentStore<T>
    where
        T: Component + 'static,
    {
        let key = TypeId::of::<ComponentStore<T>>();

        self.stores
            .entry(key)
            .or_insert_with(|| Box::new(ComponentStore::<T>::default()));

        self.stores
            .get_mut(&key)
            .unwrap()
            .downcast_mut::<ComponentStore<T>>()
            .unwrap()
    }

    pub fn insert_component<T>(&mut self, entity: Entity, component: T)
    where
        T: Component + Serialize + for<'de> Deserialize<'de> + Clone + Default + 'static,
    {
        // Store in the typed store (engine code can still use it directly)
        self.get_store_mut::<T>().insert(entity, component.clone());
        self.invoke_on_insert::<T>(entity);
    }

    /// Insert a component on an existing entity.
    /// If the component already exists it will be overwritten.
    pub fn add_component_to_entity<T>(&mut self, entity: Entity, component: T)
    where
        T: Component + Serialize + for<'de> Deserialize<'de> + Clone + Default + 'static,
    {
        // Store it in the typed store – the same place the engine uses directly.
        self.get_store_mut::<T>().insert(entity, component);
        self.invoke_on_insert::<T>(entity);
    }

    /// Replace a component wholesale through the store.
    pub fn replace_component<T>(&mut self, entity: Entity, component: T)
    where
        T: Component + Serialize + for<'de> Deserialize<'de> + Clone + Default + 'static,
    {
        debug_assert!(
            !Self::component_has_lifecycle_hooks::<T>(),
            "replace_component bypasses lifecycle hooks for {}. Use insert_component or remove_component instead.",
            std::any::type_name::<T>()
        );
        self.get_store_mut::<T>().remove(entity);
        self.get_store_mut::<T>().insert(entity, component);
    }

    /// Returns the player Entity if one exists.
    pub fn get_player_entity(&self) -> Option<Entity> {
        self.get_store::<Player>().data.keys().next().copied()
    }

    /// Returns the player Transform if a player exists.
    pub fn get_player_transform(&self) -> Option<Transform> {
        let player_entity = self.get_player_entity()?;

        self.get_store::<Transform>().get(player_entity).cloned()
    }

    /// Returns the player proxy for a given room, if one exists.
    pub fn get_player_proxy(&self, room_id: RoomId) -> Option<Entity> {
        let proxy_store = self.get_store::<PlayerProxy>();
        let room_store = self.get_store::<CurrentRoom>();

        proxy_store
            .data
            .keys()
            .find(|e| room_store.get(**e).is_some_and(|r| r.0 == room_id))
            .copied()
    }

    /// Sets the player's spawn position from the proxy in the given room.
    /// Call this before purging proxies to preserve the spawn location.
    pub fn set_player_spawn_from_proxy(&mut self, room_id: RoomId) {
        let spawn_pos = self
            .get_player_proxy(room_id)
            .and_then(|e| self.get::<Transform>(e))
            .map(|t| t.position);

        if let Some(pos) = spawn_pos
            && let Some(player_entity) = self.get_player_entity()
        {
            if let Some(transform) = self.get_mut::<Transform>(player_entity) {
                transform.position = pos;
            } else {
                self.add_component_to_entity(
                    player_entity,
                    Transform {
                        position: pos,
                        ..Default::default()
                    },
                );
            }
            self.add_component_to_entity(player_entity, CurrentRoom(room_id));
        }
    }

    /// Removes all PlayerProxy entities from the ECS.
    /// Used when preparing game data for playtest or export.
    pub fn purge_proxies(&mut self) {
        let proxy_entities: Vec<Entity> = self
            .get_store::<PlayerProxy>()
            .data
            .keys()
            .copied()
            .collect();

        for entity in proxy_entities {
            for reg in inventory::iter::<ComponentRegistry> {
                // Run on_remove for proxies that have lifecycle hooks
                if (reg.has)(self, entity) {
                    let mut boxed = (reg.clone)(self, entity);
                    (reg.on_remove)(&mut *boxed, &entity, self);
                }
                (reg.remove)(self, entity);
            }
        }
    }

    /// Recalculate next_entity_id from the highest entity id across all component stores.
    pub(crate) fn restore_next_entity_id(&mut self) {
        self.next_entity_id = inventory::iter::<ComponentRegistry>
            .into_iter()
            .filter_map(|reg| {
                self.stores
                    .get(&reg.type_id)
                    .and_then(|any_box| (reg.max_entity_id)(&**any_box))
            })
            .max()
            .map(|max_id| max_id + 1)
            .unwrap_or(1);
    }

    /// Call on_insert for the given component type and entity.
    pub(crate) fn invoke_on_insert<T: Component + 'static>(&mut self, entity: Entity) {
        let store_tid = std::any::TypeId::of::<ComponentStore<T>>();
        if let Some(reg) = inventory::iter::<ComponentRegistry>
            .into_iter()
            .find(|r| r.type_id == store_tid)
        {
            // Take the component out to avoid borrow conflicts,
            // call on_insert on the extracted value, then re-insert.
            if let Some(component) = self.get_store_mut::<T>().take(entity) {
                let mut boxed: Box<dyn Any> = Box::new(component);
                (reg.on_insert)(&mut *boxed, &entity, self);
                if let Ok(component) = boxed.downcast::<T>() {
                    self.get_store_mut::<T>().insert(entity, *component);
                }
            }
        }
    }

    /// Re-runs a registry-backed `on_insert` hook for a component already stored on an entity.
    pub(crate) fn run_registered_on_insert(
        &mut self,
        reg: &ComponentRegistry,
        entity: Entity,
    ) {
        let mut boxed = (reg.clone)(self, entity);
        (reg.on_insert)(&mut *boxed, &entity, self);
        (reg.inserter)(self, entity, boxed);
    }

    /// Check if a component type has any lifecycle hooks registered.
    fn component_has_lifecycle_hooks<T: 'static>() -> bool {
        let store_tid = std::any::TypeId::of::<ComponentStore<T>>();
        inventory::iter::<ComponentRegistry>
            .into_iter()
            .find(|r| r.type_id == store_tid)
            .map(|reg| {
                reg.on_insert as *const () != noop_on_insert as *const ()
                    || reg.on_remove as *const () != noop_on_remove as *const ()
            })
            .unwrap_or(false)
    }
}

impl Serialize for Ecs {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        // Build the dynamic component list
        let mut components = Vec::new();

        for (type_id, any_box) in &self.stores {
            // Find the registry entry that matches this TypeId
            let type_name = TYPE_NAME_FOR_ID.get(type_id);
            let type_name = match type_name {
                Some(name) => name,
                None => {
                    // Fallback
                    eprintln!(
                        "Skipping unknown component store (TypeId = {:?}) – \
                         it will not be saved. Add `ecs_component!` for the type to keep it.",
                        type_id
                    );
                    continue;
                }
            };
            let reg = inventory::iter::<ComponentRegistry>()
                .into_iter()
                .find(|r| r.type_name == *type_name)
                .expect("registry entry missing");

            // Convert the concrete store (`any_box`) into a RON value
            let ron_string = (reg.to_ron)(&**any_box);
            components.push(StoredComponent {
                type_name: reg.type_name.to_string(),
                data: ron_string,
            });
        }

        components.sort_by(|left, right| left.type_name.cmp(&right.type_name));

        // Serialize just the components; next_entity_id is derived on load
        let mut state = serializer.serialize_struct("Ecs", 1)?;
        state.serialize_field("components", &components)?;
        state.end()
    }
}

impl<'de> Deserialize<'de> for Ecs {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        #[derive(Deserialize)]
        struct Helper {
            pub components: Vec<StoredComponent>,
        }

        let helper = Helper::deserialize(deserializer)?;

        // Rebuild the component map
        let mut stores = HashMap::new();
        for stored in &helper.components {
            // Try to find a registry entry
            let reg_opt =
                inventory::iter::<ComponentRegistry>().find(|r| r.type_name == stored.type_name);

            let reg = match reg_opt {
                Some(r) => r,
                None => {
                    // Unknown component
                    eprintln!(
                        "Skipping unknown component '{}' (probably removed or renamed).",
                        stored.type_name
                    );
                    continue;
                }
            };
            let any_box = (reg.from_ron)(stored.data.clone());
            let type_id = reg.type_id;
            stores.insert(type_id, any_box);
        }

        let mut ecs = Ecs {
            stores,
            next_entity_id: 1,
            room_entities: HashMap::new(),
        };
        ecs.restore_next_entity_id();
        Ok(ecs)
    }
}

static TYPE_NAME_FOR_ID: Lazy<HashMap<TypeId, &'static str>> = Lazy::new(|| {
    let mut map = HashMap::new();
    for reg in inventory::iter::<ComponentRegistry> {
        map.insert(reg.type_id, reg.type_name);
    }
    map
});

impl Ecs {
    /// Call on_insert for every component on every entity.
    pub fn finalize_after_load(&mut self) {
        let registry_for_type_id: HashMap<TypeId, &ComponentRegistry> =
            inventory::iter::<ComponentRegistry>
                .into_iter()
                .map(|reg| (reg.type_id, reg))
                .collect();

        // Collect (entity, type_id) pairs to avoid borrow conflicts
        let mut to_finalize: Vec<(Entity, TypeId)> = Vec::new();
        for (type_id, any_box) in &self.stores {
            if let Some(reg) = registry_for_type_id.get(type_id)
                && let Some(max) = (reg.max_entity_id)(&**any_box)
            {
                    for id in 0..=max {
                        let entity = Entity(id);
                        if (reg.has)(self, entity) {
                            to_finalize.push((entity, *type_id));
                        }
                    }
                }
        }

        // Call on_insert for each collected pair, then write back the modified component.
        for (entity, type_id) in &to_finalize {
            if let Some(reg) = registry_for_type_id.get(type_id) {
                self.run_registered_on_insert(reg, *entity);
            }
        }

        // Rebuild room membership from CurrentRoom components
        self.rebuild_room_entities();
    }
}
