use super::{
    load_startup_for_game_name, load_startup_from_resources,
    rebootstrap::{entry_mode_for_intent, StartupIntent, StartupRequest},
    runtime_icon::playtest_game_name_from_payload as parse_playtest_game_name, StartupAsset,
    StartupScreenContent, StartupScreenSpec,
};
use crate::engine::{Engine, EngineBuilder, EngineEntryMode, GameInstance, SaveRuntime};
use crate::save_system::{apply_document_phase, RestorePhase};
use crate::scripting::script_system::ScriptSystem;
use bishop::prelude::*;
use engine_core::prelude::*;
use ron::de::from_str;
use std::cell::RefCell;
use std::fs;
use std::path::{Path, PathBuf};
use std::rc::Rc;

/// The source for runtime startup.
#[derive(Clone, Debug, PartialEq)]
pub enum StartupSource {
    /// Load the shipped game from the game binary's `Resources/` folder.
    Game,
    /// Load a playtest payload generated by the editor.
    Playtest { payload_path: String },
}

#[derive(serde::Deserialize)]
struct PlaytestPayload {
    room: Room,
    game: Game,
    startup_ron: Option<String>,
    #[serde(default)]
    startup_mode: StartupMode,
}

pub(crate) enum LoadedStartupData {
    Game {
        startup_asset: StartupAsset,
        game: Game,
    },
    Playtest {
        startup_asset: StartupAsset,
        room: Room,
        game: Game,
        startup_mode: StartupMode,
    },
}

pub(crate) enum LoadedStartupFiles {
    Game {
        resources_dir: PathBuf,
        startup_ron: Option<String>,
        game_ron: String,
    },
    Playtest {
        payload_ron: String,
    },
}

/// Bootstrap controller that renders startup screens until the runtime `Engine` is ready.
pub struct StartupController {
    startup_asset: StartupAsset,
    load_task: BackgroundTask<Result<LoadedStartupFiles, String>>,
    loaded: Option<LoadedStartupData>,
    intent: StartupIntent,
    source: StartupSource,
    splash_index: usize,
    splash_started_at_secs: Option<f64>,
    fallback_started_at_secs: Option<f64>,
    error: Option<String>,
}

impl StartupController {
    /// Creates a startup controller from the given [`StartupRequest`](StartupRequest).
    pub fn from_request(request: StartupRequest) -> Self {
        let intent = request.intent.clone();
        Self::new_with_intent(request.source, intent)
    }

    /// Creates a startup controller for the given source and intent.
    pub fn new_with_intent(source: StartupSource, intent: StartupIntent) -> Self {
        let startup_asset = load_initial_startup(&source);
        let source_for_task = source.clone();
        Self {
            startup_asset,
            load_task: BackgroundTask::spawn(move || load_startup_data(source_for_task)),
            loaded: None,
            intent,
            source,
            splash_index: 0,
            splash_started_at_secs: None,
            fallback_started_at_secs: None,
            error: None,
        }
    }

    /// Creates a startup controller for the given source.
    pub fn new(source: StartupSource) -> Self {
        Self::new_with_intent(source, StartupIntent::Raw)
    }

    /// Advances bootstrap and returns the fully-built engine once ready.
    pub async fn frame(&mut self, ctx: PlatformContext) -> Option<Engine> {
        if let Some(error) = &self.error {
            render_error_screen(&ctx, error);
            return None;
        }

        if self.loaded.is_none() {
            if let Some(result) = self.load_task.poll() {
                match result {
                    Ok(files) => match parse_startup_data(files) {
                        Ok(loaded) => {
                            self.startup_asset = loaded.startup_asset().clone();
                            self.loaded = Some(loaded);
                        }
                        Err(error) => self.error = Some(error),
                    },
                    Err(error) => {
                        self.error = Some(error);
                    }
                }
            }
        }

        if let Some(error) = &self.error {
            render_error_screen(&ctx, error);
            return None;
        }

        if self
            .loaded
            .as_ref()
            .is_some_and(LoadedStartupData::skips_startup_presentation)
            || self.intent == StartupIntent::LoadLatest
        {
            let loaded = self.loaded.take()?;
            let request = StartupRequest {
                source: self.source.clone(),
                intent: self.intent.clone(),
            };
            match try_build_engine(ctx, request, loaded) {
                Ok(engine) => return Some(engine),
                Err(error) => {
                    self.error = Some(error);
                    return None;
                }
            }
        }

        if let Some(screen) = self
            .startup_asset
            .loading
            .splash_screens
            .get(self.splash_index)
        {
            render_screen(&ctx, screen);
            let now = ctx.borrow().get_time();
            let started_at = self.splash_started_at_secs.get_or_insert(now);
            if splash_min_duration_elapsed(*started_at, now, screen.min_duration_secs) {
                self.splash_started_at_secs = None;
                self.splash_index += 1;
            }
            return None;
        }

        render_screen(&ctx, &self.startup_asset.loading.fallback_screen);

        let now = ctx.borrow().get_time();
        let started_at = self.fallback_started_at_secs.get_or_insert(now);
        if !splash_min_duration_elapsed(
            *started_at,
            now,
            self.startup_asset.loading.fallback_screen.min_duration_secs,
        ) {
            return None;
        }

        self.fallback_started_at_secs = None;
        let loaded = self.loaded.take()?;
        let request = StartupRequest {
            source: self.source.clone(),
            intent: self.intent.clone(),
        };
        let result = try_build_engine(ctx, request, loaded);
        match result {
            Ok(engine) => Some(engine),
            Err(error) => {
                self.error = Some(error);
                None
            }
        }
    }
}

impl LoadedStartupData {
    fn startup_asset(&self) -> &StartupAsset {
        match self {
            Self::Game { startup_asset, .. } | Self::Playtest { startup_asset, .. } => {
                startup_asset
            }
        }
    }

    pub(crate) fn skips_startup_presentation(&self) -> bool {
        matches!(
            self,
            Self::Playtest {
                startup_mode: StartupMode::Skip,
                ..
            }
        )
    }
}

fn load_startup_data(source: StartupSource) -> Result<LoadedStartupFiles, String> {
    match source {
        StartupSource::Game => {
            let resources_dir = resources_dir_from_exe()
                .ok_or_else(|| "Could not find game resources folder.".to_string())?;
            let startup_path = resources_dir.join(paths::STARTUP_RON);
            let startup_ron = fs::read_to_string(&startup_path).ok();
            let game_path = resources_dir.join(paths::GAME_RON);
            let game_ron = fs::read_to_string(&game_path)
                .map_err(|error| format!("Could not read '{}': {error}", game_path.display()))?;
            Ok(LoadedStartupFiles::Game {
                resources_dir,
                startup_ron,
                game_ron,
            })
        }
        StartupSource::Playtest { payload_path } => {
            let payload_str = fs::read_to_string(&payload_path)
                .map_err(|error| format!("Could not read playtest payload: {error}"))?;
            Ok(LoadedStartupFiles::Playtest {
                payload_ron: payload_str,
            })
        }
    }
}

fn load_initial_startup(source: &StartupSource) -> StartupAsset {
    match source {
        StartupSource::Game => resources_dir_from_exe()
            .map(|resources_dir| load_startup_from_resources(&resources_dir))
            .unwrap_or_default(),
        StartupSource::Playtest { payload_path } => {
            load_playtest_startup_preview(Path::new(payload_path)).unwrap_or_default()
        }
    }
}

pub(crate) fn load_playtest_startup_preview(payload_path: &Path) -> Option<StartupAsset> {
    #[derive(serde::Deserialize)]
    struct PayloadStartupPreview {
        startup_ron: Option<String>,
    }

    let payload_ron = fs::read_to_string(payload_path).ok()?;
    let preview = from_str::<PayloadStartupPreview>(&payload_ron).ok()?;
    if let Some(startup_ron) = preview.startup_ron.as_deref() {
        return Some(parse_payload_startup(startup_ron));
    }
    let game_name = parse_playtest_game_name(&payload_ron)?;
    Some(load_startup_for_game_name(&game_name))
}

pub(crate) fn parse_startup_data(files: LoadedStartupFiles) -> Result<LoadedStartupData, String> {
    match files {
        LoadedStartupFiles::Game {
            resources_dir,
            startup_ron,
            game_ron,
        } => {
            let startup_asset = parse_startup(startup_ron.as_deref(), &resources_dir);
            let game = from_str::<Game>(&game_ron)
                .map_err(|error| format!("Failed to parse game.ron: {error}"))?;
            Ok(LoadedStartupData::Game {
                startup_asset,
                game,
            })
        }
        LoadedStartupFiles::Playtest { payload_ron } => {
            let PlaytestPayload {
                room,
                game,
                startup_ron,
                startup_mode,
            } = from_str(&payload_ron)
                .map_err(|error| format!("Failed to deserialize playtest payload: {error}"))?;
            let startup_asset = startup_ron
                .as_deref()
                .map(parse_payload_startup)
                .unwrap_or_else(|| load_startup_for_game_name(&game.name));
            Ok(LoadedStartupData::Playtest {
                startup_asset,
                room,
                game,
                startup_mode,
            })
        }
    }
}

fn parse_startup(startup_ron: Option<&str>, resources_dir: &Path) -> StartupAsset {
    let Some(startup_ron) = startup_ron else {
        return StartupAsset::default();
    };

    ron::from_str(startup_ron).unwrap_or_else(|error| {
        onscreen_error!(
            "Failed to parse startup '{}': {}",
            resources_dir.join(paths::STARTUP_RON).display(),
            error
        );
        StartupAsset::default()
    })
}

fn parse_payload_startup(startup_ron: &str) -> StartupAsset {
    ron::from_str(startup_ron).unwrap_or_else(|error| {
        onscreen_error!("Failed to parse embedded playtest startup: {}", error);
        StartupAsset::default()
    })
}

fn try_build_engine(
    ctx: PlatformContext,
    request: StartupRequest,
    loaded: LoadedStartupData,
) -> Result<Engine, String> {
    // Register save Lua context before any bootstrap scripts run so that
    // scripts can register save providers during load.
    let mut builder = EngineBuilder::new();
    builder
        .register_save_context()
        .map_err(|e| format!("Failed to register save Lua context: {e}"))?;

    match request.intent {
        StartupIntent::Raw => match loaded {
            LoadedStartupData::Game {
                startup_asset,
                game,
            } => {
                set_engine_mode(EngineMode::Game);
                set_game_name(game.name.clone());

                let entry_mode = resolve_entry_mode(&startup_asset, &game, StartupMode::Full);
                builder = builder.entry_mode(entry_mode);
                let game_instance = {
                    let mut ctx_ref = ctx.borrow_mut();
                    GameInstance::from_loaded_game(
                        &mut *ctx_ref,
                        game,
                        &builder.lua,
                        &mut builder.camera_manager,
                    )
                };

                Ok(builder.assemble(game_instance, ctx, false))
            }
            LoadedStartupData::Playtest {
                startup_asset,
                room,
                game,
                startup_mode,
            } => {
                set_engine_mode(EngineMode::Playtest);
                set_game_name(game.name.clone());

                let entry_mode = resolve_entry_mode(&startup_asset, &game, startup_mode);
                builder = builder.entry_mode(entry_mode);
                let game_instance = {
                    let mut ctx_ref = ctx.borrow_mut();
                    GameInstance::from_loaded_room(
                        &mut *ctx_ref,
                        room,
                        game,
                        &builder.lua,
                        &mut builder.camera_manager,
                    )
                };

                Ok(builder.assemble(game_instance, ctx, true))
            }
        },
        StartupIntent::LoadLatest => {
            let is_playtest = matches!(loaded, LoadedStartupData::Playtest { .. });
            let game_name = match &loaded {
                LoadedStartupData::Game { game, .. }
                | LoadedStartupData::Playtest { game, .. } => game.name.clone(),
            };
            set_engine_mode(if is_playtest {
                EngineMode::Playtest
            } else {
                EngineMode::Game
            });
            set_game_name(game_name);

            let save_runtime = SaveRuntime::new(builder.save_providers.clone(), builder.pending_quit_to_title.clone());

            let document = save_runtime
                .load_latest_document()
                .map_err(|e| format!("Failed to read save document: {e}"))?
                .ok_or_else(|| "No save data found for explicit load".to_string())?;

            apply_document_phase(
                &mut builder.save_providers.borrow_mut(),
                &document,
                RestorePhase::PreRuntime,
            )
            .map_err(|e| format!("Failed to apply PreRuntime restore: {e}"))?;

            let prepared = match loaded {
                LoadedStartupData::Game { game, .. } => {
                    GameInstance::prepare_loaded_game(&builder.lua, game)
                }
                LoadedStartupData::Playtest { room, game, .. } => {
                    GameInstance::prepare_loaded_room(&builder.lua, room, game)
                }
            };

            let game_instance = {
                let mut ctx_ref = ctx.borrow_mut();
                GameInstance::from_prepared(&mut *ctx_ref, prepared, &mut builder.camera_manager)
            };

            ScriptSystem::init(&builder.lua, &game_instance.game.script_manager.event_bus);

            let entry_mode =
                entry_mode_for_intent(&StartupIntent::LoadLatest, EngineEntryMode::Playing);
            let game_instance = Rc::new(RefCell::new(game_instance));
            let mut engine = builder
                .entry_mode(entry_mode)
                .into_engine(game_instance, ctx.clone(), save_runtime, is_playtest);

            {
                let mut game_ref = engine.game_instance.borrow_mut();
                let game_ctx = game_ref.game.ctx_mut();
                ScriptSystem::load_scripts(&engine.lua, game_ctx.ecs, game_ctx.script_manager)
                    .map_err(|e| format!("Failed to prime scripts for runtime restore: {e}"))?;
            }

            apply_document_phase(
                &mut engine.save_runtime.providers().borrow_mut(),
                &document,
                RestorePhase::PostRuntime,
            )
            .map_err(|e| format!("Failed to apply PostRuntime restore: {e}"))?;

            ScriptSystem::process_commands(&mut engine);
            engine.rebuild_camera_from_loaded_state();
            Ok(engine)
        }
    }
}

fn resolve_entry_mode(
    startup_asset: &StartupAsset,
    game: &Game,
    startup_mode: StartupMode,
) -> EngineEntryMode {
    if startup_mode == StartupMode::Skip {
        return EngineEntryMode::Playing;
    }

    let menu_id = startup_asset.start_menu_id.trim();
    if menu_id.is_empty() {
        return EngineEntryMode::Playing;
    }

    if !menu_template_exists(menu_id) {
        onscreen_error!(
            "Startup menu '{}' is missing for game '{}'; falling back to Playing.",
            menu_id,
            game.name
        );
        return EngineEntryMode::Playing;
    }

    EngineEntryMode::StartMenu {
        menu_id: menu_id.to_string(),
    }
}

fn menu_template_exists(menu_id: &str) -> bool {
    let dir = menus_folder();
    let Ok(entries) = fs::read_dir(dir) else {
        return false;
    };

    for entry in entries.filter_map(Result::ok) {
        let path = entry.path();
        if path.extension().is_none_or(|ext| ext != "ron") {
            continue;
        }
        let Ok(ron_str) = fs::read_to_string(&path) else {
            continue;
        };
        let Ok(template) = ron::from_str::<MenuTemplate>(&ron_str) else {
            continue;
        };
        if template.id == menu_id {
            return true;
        }
    }

    false
}

fn render_error_screen(ctx: &PlatformContext, error: &str) {
    let screen = StartupScreenSpec {
        min_duration_secs: 0.0,
        background_color: [0.1, 0.0, 0.0, 1.0],
        content: StartupScreenContent::Text {
            text: error.to_string(),
            font_size: 32.0,
            color: [1.0, 0.9, 0.9, 1.0],
        },
    };
    render_screen(ctx, &screen);
}

fn render_screen(ctx: &PlatformContext, screen: &StartupScreenSpec) {
    let mut ctx_ref = ctx.borrow_mut();
    let ctx = &mut *ctx_ref;
    ctx.clear_background(screen.background_color.into());

    match &screen.content {
        StartupScreenContent::Text {
            text,
            font_size,
            color,
        } => draw_centered_text(ctx, text, *font_size, (*color).into()),
    }
}

fn draw_centered_text(ctx: &mut impl BishopContext, text: &str, font_size: f32, color: Color) {
    let dims = ctx.measure_text(text, font_size);
    let x = (ctx.screen_width() - dims.width) * 0.5;
    let y = (ctx.screen_height() + dims.height) * 0.5;
    ctx.draw_text(text, x, y, font_size, color);
}

pub(crate) fn splash_min_duration_elapsed(
    started_at_secs: f64,
    now_secs: f64,
    min_duration_secs: f32,
) -> bool {
    (now_secs - started_at_secs) >= min_duration_secs as f64
}
