// editor/src/commands/asset/tests/mod.rs
mod batch_delete_cmd_tests;
mod create_directory_cmd_tests;
mod delete_asset_cmd_tests;
mod delete_directory_cmd_tests;
mod delete_unregistered_file_cmd_tests;
mod remap_asset_path_cmd_tests;
mod rename_asset_cmd_tests;
mod rename_directory_cmd_tests;
